import os
import sys
def find_prj_root(path=os.getcwd()):
    if os.path.isfile(os.path.join(path,'.PRJ_ROOT')):
        return path
    else:
        if path:
            return find_prj_root(os.path.dirname(path))
        else:
            raise Exception('Can not find the PRJ_ROOT directory')

PRJ_ROOT=find_prj_root()

BIOINFO_ROOT = os.getenv('BIOINFO_ROOT')
SNAKE_ROOT=os.getenv('SNAKE_ROOT')

BIN_DIR=PRJ_ROOT+'/local/bin'
SRC_DIR=PRJ_ROOT+'/local/src'
DATA_DIR=PRJ_ROOT+'/local/share/data'
sys.path.append(SRC_DIR)

SAMPLES=['CRC0327_cetux_2',
'CRC0322_NT_1_3000',
'CRC0322_cetux_1',
'CRC0542_CTX72h_1',
'CRC0542_NT72h_1',
'CRC0327_NT_2',
'CRC0069_NT72h_1',
'CRC0069_CTX72h_1',
'CRC0322LMX_CTX1w_1_singleron0722',
'CRC0322LMX_NT1w_1_singleron0722']
SAMPLES_NI=['CRC0327_cetux_2',
'CRC0322_NT_1_3000',
'CRC0322_cetux_1',
'CRC0542_CTX72h_1',
'CRC0542_NT72h_1',
'CRC0327_NT_2',
'CRC0069_NT72h_1',
'CRC0069_CTX72h_1']

KRAS=['CRC1502_cetux_1','CRC1502_NT_1','CRC1620_cetux_1','CRC1620_NT_1']

SAMPLES_INVIVO_LMO=['CRC0322LMO_CTX72h_1_singleron0722',
'CRC0322LMO_NT72h_1_singleron0722',
'CRC0322LMX_CTX1w_1_singleron0722',
'CRC0322LMX_NT1w_1_singleron0722',
]
SAMPLES_INVIVO=[
'CRC0322LMX_CTX1w_1_singleron0722',
'CRC0322LMX_NT1w_1_singleron0722',
]

SAMPLES_GAE= [
    "KUL01-B", "KUL01-N", "KUL01-T",
    "KUL19-B", "KUL19-N", "KUL19-T",
    "KUL21-B", "KUL21-N", "KUL21-T",
    "KUL28-B", "KUL28-N", "KUL28-T",
    "KUL30-B", "KUL30-N", "KUL30-T",
    "KUL31-B", "KUL31-N", "KUL31-T",
    "SMC01-N", "SMC01-T",
    "SMC02-N", "SMC02-T",
    "SMC03-N", "SMC03-T",
    "SMC04-N", "SMC04-T",
    "SMC05-N",
    "SMC06-N", "SMC06-T",
    "SMC07-N", "SMC07-T",
    "SMC08-N", "SMC08-T",
    "SMC09-N", "SMC09-T",
    "SMC10-N", "SMC10-T",
    "SMC11-T",
    "SMC14-T",
    "SMC15-T",
    "SMC16-T",
    "SMC17-T",
    "SMC18-T",
    "SMC19-T",
    "SMC20-T",
    "SMC21-T",
    "SMC22-T",
    "SMC23-T",
    "SMC24-T",
    "SMC25-T",
]


# parziale lista di campioni in vitro con chiamate del ciclo fatte senza saver (gli in vivo sono solo così perchè con saver danno errori)
SAMPLES_A_MUCCA=['CRC0327_cetux_2',
'CRC0322_NT_1_3000',
'CRC0322_cetux_1',
'CRC0327_NT_2'
]

SAMPLES_TC=['CRC0322_12d_EGF','CRC0322_12d_NOEGF','CRC0322_3d_CTX','CRC0322_4d_EGF','CRC0322_4d_NOEGF','CRC0322_7d_CTX','CRC0322_8d_EGF','CRC0322_8d_NOEGF']